title: Xiaohui Xie's GitHub Site
description: >- 
  A simple Jekyll site that renders Markdown into HTML
baseurl: ""   # IMPORTANT: leave empty for user sites
url: "https://xhx.github.io"   # replace with your GitHub username

# theme: minima   # built-in GitHub Pages theme (commented out for custom layouts)
markdown: kramdown

