title: Xiaohui Xie @ UC Irvine
baseurl: ""   # IMPORTANT: leave empty for user sites
url: "https://xhx.github.io"   # replace with your GitHub username
github_username: xhx

# theme: minima   # built-in GitHub Pages theme (commented out for custom layouts)
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false

