# Site settings
title: "Xiaohui Xie - Professor of Computer Science"
description: "Personal website of Xiaohui Xie, Professor of Computer Science at UC Irvine. Research in AI/ML, Computer Vision, and AI for Science."
url: "https://xhx.github.io"
baseurl: ""

# Author information
author:
  name: "Xiaohui Xie"
  email: "xhx@uci.edu"
  bio: "Professor of Computer Science at UC Irvine"
  location: "Irvine, California"
  links:
    - label: "UC Irvine"
      icon: "fas fa-university"
      url: "https://www.uci.edu/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID&sortby=pubdate"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections - This enables automatic page generation from markdown files
collections:
  pages:
    output: true
    permalink: /:path/
  math:
    output: true
    permalink: /math/:name/
  teaching:
    output: true
    permalink: /teaching/:name/
  ai:
    output: true
    permalink: /ai/:name/

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_sidebar: true
      show_breadcrumbs: true
  - scope:
      path: "math"
      type: "math"
    values:
      layout: "page"
      show_sidebar: true
      show_breadcrumbs: true
  - scope:
      path: "teaching"
      type: "teaching"
    values:
      layout: "page"
      show_sidebar: true
      show_breadcrumbs: true
  - scope:
      path: "ai"
      type: "ai"
    values:
      layout: "page"
      show_sidebar: true
      show_breadcrumbs: true

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include in processing
include:
  - _pages
  - _layouts
  - _includes
  - assets
  - math
  - teaching
  - ai

# Theme settings (using minima theme - GitHub Pages compatible)
theme: minima

# Minima theme customization
minima:
  social_links:
    github: xhx
    email: xhx@uci.edu
  author_page:
    layout: page
    permalink: /about/
  show_page_meta: true
  show_post_meta: true

# Kramdown settings for better markdown rendering
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Rouge syntax highlighting
rouge:
  line_numbers: false
  start_line: 1
  line_number_start: 1
  anchor_line_numbers: false
  inline_theme: github
  theme: github

# Pagination (if you want to add blog posts later)
paginate: 5
paginate_path: "/blog/page:num/"

# Sitemap settings
sitemap:
  changefreq: monthly
  priority: 0.8
  lastmod: 2024-01-01

# SEO settings
seo:
  title: "Xiaohui Xie - Professor of Computer Science at UC Irvine"
  description: "Research in AI/ML, Computer Vision, and AI for Science. Professor at UC Irvine Department of Computer Science."
  author: "Xiaohui Xie"
  image: "/assets/images/profile.jpg"
  type: "website"
